"""Command-line interface for the evidence-producing harness."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tempfile
from typing import Any, Sequence

from dcp_harness import __version__
from dcp_harness.adapter import load_adapter
from dcp_harness.backend import ClaudeCodeBackend, RecordedBackend
from dcp_harness.config import load_config, template
from dcp_harness.runtime import Harness
from dcp_harness.util import HarnessError, load_json_object, write_json


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="dcp-harness",
        description="Capture and challenge an Auto Research run under DCP.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="create a minimal audit project")
    init_parser.add_argument("directory")
    init_parser.add_argument(
        "--force", action="store_true",
        help="add missing files in an existing directory; never overwrite files",
    )

    doctor = subparsers.add_parser("doctor", help="check the frozen adapter and agent backend")
    doctor.add_argument("--config", required=True)
    doctor.add_argument("--json", action="store_true")

    for command, help_text in (
        ("capture", "run and capture the main Auto Research lineage"),
        ("challenge", "run registered no-lineage challengers"),
        ("gate3", "run truthful, neutral, and sham pairs"),
        ("finalize", "build and replay-check the DCP Bundle"),
        ("run", "run capture, challenge, Gate 3, and finalization"),
        ("status", "show resumable run state"),
    ):
        item = subparsers.add_parser(command, help=help_text)
        item.add_argument("--config", required=True)
        item.add_argument("--run", required=True)
        item.add_argument("--json", action="store_true")
    return parser


def _emit(value: dict[str, Any], *, raw_json: bool) -> None:
    if raw_json:
        print(json.dumps(value, ensure_ascii=False, sort_keys=True))
        return
    if "phases" in value:
        print(f"DCP run {value['run_id']} for {value['claim_id']}")
        for phase, status in value["phases"].items():
            print(f"  {phase:10s} {status}")
        print(f"  ledger     {'valid' if value.get('ledger_valid') else 'INVALID'}")
        if value.get("bundle"):
            print(f"  bundle     {value['bundle']}")
        return
    if "verdict" in value:
        verdict = value["verdict"]
        print(f"Bundle {value['bundle_id']}")
        print(f"  Core       {verdict['core']}")
        print(f"  Evidence   {verdict['evidence']}")
        print(f"  replay     {'verified' if value['kernel_replay_matches'] else 'FAILED'}")
        return
    print(json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2))


_ADAPTER_TEMPLATE = '''"""Trusted task adapter generated by dcp-harness init.

Keep private labels and verifier logic outside the agent workspace. Fill in
the methods below before starting a prospective audit.
"""

from dcp import Registration
from dcp.registration import (
    PAIR_REPLACEMENT_POLICY_NONE,
    PAIR_REPLACEMENT_POLICY_TRANSPORT,
)
from dcp_harness import (
    AuditMaterials,
    AuditAttestations,
    BaseTaskAdapter,
    EpisodeEvaluation,
    assemble_evidence,
)


class TaskAdapter(BaseTaskAdapter):
    def audit_materials(self):
        # Return AuditMaterials with SHA-256 digests of the exact private
        # verifier, held-out-unit manifest, baseline, and branch policies.
        # The harness will not start until all six materials are sealed.
        raise NotImplementedError("seal task-specific audit materials")

    def registration(self, context):
        c = context.contracts
        replacement_policy = (
            PAIR_REPLACEMENT_POLICY_TRANSPORT
            if context.config.audit.max_feedback_pair_replacements
            or context.config.audit.max_sham_pair_replacements
            else PAIR_REPLACEMENT_POLICY_NONE
        )
        # All values below are sealed before the main run. Choose them from a
        # power/cost plan, never from observed outcomes.
        return Registration(
            claim_id=context.config.claim_id,
            audit_family_id="replace-with-audit-family-v1",
            model_id=context.config.agent.model,
            interface_hash=context.interface_hash,
            task_family_profile="replace-with-task-family-v1",
            grade_requested="evidence",
            inference_scope="exhaustive_finite_set",
            ci_method="finite_set_exact",
            feedback_inference_scope="sampled_population",
            feedback_ci_method="paired_binary_exact",
            sham_inference_scope="sampled_population",
            sham_ci_method="paired_binary_exact",
            delta_min=0.05,
            kappa=0.5,
            m_max=162,
            min_n_ind=90,
            gate2_control_contract_hash=c["gate2_control_contract_hash"],
            challenge_distribution_hash=c["challenge_distribution_hash"],
            alpha_main=0.005,
            alpha_score=0.005,
            alpha_recovery=0.01,
            alpha_adequacy=0.005,
            alpha_evidence=0.01,
            alpha_sham=0.01,
            alpha_neutral=0.005,
            delta_evidence=0.34,
            delta_sham=0.17,
            feedback_estimand="binary",
            feedback_utility_mapping="canonical_p_wrapper_v1",
            registered_n_feedback_pairs=context.config.audit.feedback_pairs,
            registered_n_sham_pairs=context.config.audit.sham_pairs,
            gate3_pair_replacement_policy=replacement_policy,
            max_feedback_pair_replacements=context.config.audit.max_feedback_pair_replacements,
            max_sham_pair_replacements=context.config.audit.max_sham_pair_replacements,
            scaffold_hash=c["scaffold_hash"],
            feedback_schema_hash=c["feedback_schema_hash"],
            sham_operator_hash=c["sham_operator_hash"],
            utility_scale_id="replace-with-registered-binary-utility-v1",
            sham_calibration_id="replace-with-confirmatory-sham-calibration-v1",
            gate3_checkpoint_scope=context.config.audit.checkpoint_scope,
            gate3_paired_arm_contract_hash=c["gate3_paired_arm_contract_hash"],
            gate3_truthful_arm_contract_hash=c["gate3_truthful_arm_contract_hash"],
            gate3_neutral_arm_contract_hash=c["gate3_neutral_arm_contract_hash"],
            gate3_neutral_recovery_contract_hash=c["gate3_neutral_recovery_contract_hash"],
            gate3_checkpoint_selection_rule_hash=c["selection_rule_hash"],
            gate3_resource_contract_hash=c["gate3_resource_contract_hash"],
            gate3_opportunity_contract_hash=c["gate3_opportunity_contract_hash"],
            gate3_branch_policy_hash=c["gate3_branch_policy_hash"],
            truthful_feedback_generator_hash=c["truthful_feedback_generator_hash"],
            neutral_sham_generator_hash=c["neutral_sham_generator_hash"],
            gate3_pair_randomization_distribution_hash=c["gate3_pair_randomization_distribution_hash"],
            sham_randomization_distribution_hash=c["sham_randomization_distribution_hash"],
            sham_paired_arm_contract_hash=c["sham_paired_arm_contract_hash"],
            sham_reference_arm_contract_hash=c["sham_reference_arm_contract_hash"],
            sham_proposed_arm_contract_hash=c["sham_proposed_arm_contract_hash"],
            reference_null_generator_hash=c["reference_null_generator_hash"],
            audit_slot_id=c["audit_slot_id"],
            audit_slot_reservation_receipt_hash=c["audit_slot_reservation_receipt_hash"],
        )

    def prepare_episode(self, context):
        # Copy only phase-appropriate public task material into context.workspace.
        pass

    def prompt(self, context):
        return "Describe the artifact path, objective, and allowed experiment action."

    def handle_experiment(self, context, payload):
        # Return truthful feedback for main/truthful phases and the registered
        # no-signal payload for neutral/sham phases.
        raise NotImplementedError

    def evaluate(self, context):
        # Run the sealed private verifier only after the agent commits finish.
        return EpisodeEvaluation(outcome="unresolved", reason="implement verifier")

    def baseline(self, main_context):
        return EpisodeEvaluation(outcome="unresolved", reason="implement baseline")

    def select_checkpoint(self, main_episode):
        # This rule is hashed before the run. Return a checkpoint before the
        # result-producing feedback window.
        return 0

    def build_evidence(self, run):
        # Mechanical hashes, scores, receipts, and ledgers are filled from the
        # frozen run. These booleans deliberately default to false. Set each
        # one to true only after the named task-specific audit was performed.
        return assemble_evidence(run, AuditAttestations())


adapter = TaskAdapter
'''


def _init(directory: Path, *, force: bool) -> dict[str, Any]:
    directory = directory.expanduser().resolve()
    if directory.exists() and any(directory.iterdir()) and not force:
        raise HarnessError("init directory is not empty; use --force to add missing files")
    directory.mkdir(parents=True, exist_ok=True)
    workspace = directory / "workspace"
    workspace.mkdir(exist_ok=True)
    config_path = directory / "dcp-harness.json"
    adapter_path = directory / "task_adapter.py"
    if not config_path.exists():
        write_json(config_path, template())
    if not adapter_path.exists():
        adapter_path.write_text(_ADAPTER_TEMPLATE, encoding="utf-8")
    readme = workspace / "README.txt"
    if not readme.exists():
        readme.write_text(
            "Place only the public starter workspace here. Private verifier data must stay outside this directory.\n",
            encoding="utf-8",
        )
    return {
        "created": str(directory),
        "config": str(config_path),
        "adapter": str(adapter_path),
        "workspace": str(workspace),
        "next": "edit dcp-harness.json and task_adapter.py, then run dcp-harness doctor",
    }


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "init":
            result = _init(Path(args.directory), force=args.force)
            _emit(result, raw_json=False)
            return 0
        config = load_config(args.config)
        if args.command == "doctor":
            loaded = load_adapter(config)
            with tempfile.TemporaryDirectory(prefix="dcp-harness-doctor-") as temporary:
                backend = ClaudeCodeBackend(config, run_root=Path(temporary))
                result = backend.doctor()
            result["adapter_identity_hash"] = loaded.identity_hash
            result["adapter_source_hash"] = loaded.source_hash
            _emit(result, raw_json=args.json)
            return 0 if result["ok"] else 1
        backend = None
        if args.command in {"status", "finalize"}:
            run_root = Path(args.run).expanduser().resolve()
            identity = load_json_object(
                run_root / "registration/agent_interface.json"
            )
            backend = RecordedBackend(identity)
        harness = Harness(config, args.run, backend=backend)
        result = {
            "capture": harness.capture,
            "challenge": harness.challenge,
            "gate3": harness.gate3,
            "finalize": harness.finalize,
            "run": harness.run_all,
            "status": harness.status,
        }[args.command]()
        _emit(result, raw_json=args.json)
        return 0
    except (HarnessError, OSError, ValueError) as exc:
        print(f"dcp-harness: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
